### ISSUE TITLE
Reorder images on the about page

### ISSUE THREAD

**Issue by bhermann** [upb-uc4/website#5]
I would suggest to name the team first and the supervisors below in a new row. 
Just a suggestion...

**Comment by theovier** [comment]
Having the supervisors listed first makes the project seem more "serious" in my opinion. Otherwise, it may be seen as "just a bunch of students fiddling around". However, I understand the intention of highlighting the team members. Maybe we should discuss this @upb-uc4.

**Comment by theovier** [comment]
Closed due to inactivity.
